# Generated by Django 3.2 on 2021-04-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registerdb',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
