# Generated by Django 3.2 on 2021-04-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdb',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
