# Generated by Django 3.2 on 2021-04-25 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_auto_20210425_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='managerdb',
            fields=[
                ('managerid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.registerdb')),
            ],
        ),
    ]
