# Generated by Django 3.2 on 2021-04-29 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0004_managerdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookdb',
            fields=[
                ('isbn', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)])),
                ('title', models.CharField(max_length=150)),
                ('publisher', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=20)),
                ('pubdate', models.DateField()),
                ('pages', models.IntegerField(max_length=10)),
                ('price', models.IntegerField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('currentstock', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='authordb',
            fields=[
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mystore.bookdb', validators=[django.core.validators.MinLengthValidator(13), django.core.validators.MaxLengthValidator(13)])),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('isbn', 'author')},
            },
        ),
    ]
