# Generated by Django 3.2 on 2021-04-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0005_authordb_bookdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='keywordm',
            field=models.CharField(default='null', max_length=150),
        ),
    ]
