# Generated by Django 3.2 on 2021-04-29 18:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_auto_20210429_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authordb',
            name='author',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='authordb',
            name='isbn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mystore.bookdb', unique=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
