# Generated by Django 3.2 on 2021-04-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0009_alter_authordb_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='author',
            field=models.CharField(default='empty', max_length=150),
        ),
        migrations.AddField(
            model_name='registerdb',
            name='userlevel',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
