# Generated by Django 3.2 on 2021-04-30 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0010_auto_20210430_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('score', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
            ],
        ),
        migrations.AlterField(
            model_name='bookdb',
            name='currentstock',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookdb',
            name='pages',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='bookdb',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registerdb',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='ratingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
                ('commentdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.commentdb')),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.bookdb')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.registerdb')),
            ],
        ),
        migrations.AddField(
            model_name='commentdb',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.bookdb'),
        ),
        migrations.AddField(
            model_name='commentdb',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.registerdb'),
        ),
    ]
