# Generated by Django 3.2 on 2021-04-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0012_alter_commentdb_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdb',
            name='bookscore',
            field=models.IntegerField(default=0),
        ),
    ]
