# Generated by Django 3.2 on 2021-04-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0013_commentdb_bookscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdb',
            name='score',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default='null'),
        ),
    ]
