# Generated by Django 3.2 on 2021-04-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0014_alter_commentdb_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='trust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookscore', models.IntegerField()),
                ('trustedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustedby', to='mystore.registerdb')),
                ('trusting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusting', to='mystore.registerdb')),
            ],
        ),
    ]
