# Generated by Django 3.2 on 2021-04-30 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0015_trust'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trust',
            old_name='bookscore',
            new_name='trustscore',
        ),
    ]
