# Generated by Django 3.2 on 2021-04-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0016_rename_bookscore_trust_trustscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdb',
            name='isactive',
            field=models.IntegerField(default=0),
        ),
    ]
