# Generated by Django 3.2 on 2021-05-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0017_registerdb_isactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('copies', models.PositiveIntegerField()),
                ('amaount', models.PositiveIntegerField()),
                ('order_status', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.bookdb')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mystore.registerdb')),
            ],
        ),
    ]
