# Generated by Django 3.2 on 2021-05-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0018_orderinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='amaount',
            new_name='amount',
        ),
    ]
