# Generated by Django 3.2 on 2021-05-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0020_auto_20210501_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='reqbook',
            name='requeststatus',
            field=models.CharField(default='No Updates', max_length=50),
        ),
    ]
